In [1]:
import numpy as np

### Create an array from my_list = [5, 10, 15, 20, 25]

In [2]:
my_list = [5, 10, 15, 20, 25]
my_array = np.array(my_list)
my_array

array([ 5, 10, 15, 20, 25])

### Generate an array of 5x5 with zeros.

In [3]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Generate an array of 4x4 with ones and assign data type as int.

In [4]:
np.ones((4, 4), dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### Make all the values of the array above with the value of 7.

In [5]:
np.full((4, 4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

### Create an array of even integers from 2 to 16 (inclusive).

In [6]:
np.arange(2,17,2, dtype=int)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### Create a 5x5 matrix with the values between 0 to 25 (exclusive).

In [7]:
np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace method.

In [8]:
arr = np.linspace(0, 24, 25 ,dtype= int).reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Create randomly 5 numbers with numpy.

In [9]:
np.random.randn(5, 5)

array([[ 1.25980276, -0.35572783, -0.02747978,  0.71125604,  0.56443075],
       [-0.13250271,  0.28772511,  0.57246617, -0.17247939,  0.36886771],
       [ 1.60051466, -0.12914788,  0.15133243,  0.21688316,  0.56917139],
       [ 0.48062332, -2.28051738,  0.08176959, -1.14797164, -2.11140778],
       [-0.82100123,  0.50788158,  0.71397581, -1.82040115,  0.61785092]])

### Create a 3*4 array of random int numbers between 20 and 50.

In [10]:
np.random.randint(20, 50, size=(3,4))

array([[41, 41, 28, 45],
       [34, 26, 35, 36],
       [25, 35, 24, 48]])

### Create an array named "ranarr"consisting of randomly 48 numbers and reshape this array with the shape of 6x8 in different ways.

In [11]:
ranarr = np.random.randint(0, 48, 48)
ranarr

array([23, 20, 34, 39, 24, 40, 16, 31, 44,  3, 45, 19,  1,  2, 42,  6, 35,
        0, 44,  7, 19, 16, 25, 28, 30, 33, 19, 19, 36, 46,  0,  3, 18,  2,
        5, 28, 45, 11, 45,  3, 30, 29,  3, 13, 14, 40, 43, 17])

In [12]:
ranarr.reshape(6, 8)

array([[23, 20, 34, 39, 24, 40, 16, 31],
       [44,  3, 45, 19,  1,  2, 42,  6],
       [35,  0, 44,  7, 19, 16, 25, 28],
       [30, 33, 19, 19, 36, 46,  0,  3],
       [18,  2,  5, 28, 45, 11, 45,  3],
       [30, 29,  3, 13, 14, 40, 43, 17]])

In [13]:
ranarr.reshape(-1, 8)

array([[23, 20, 34, 39, 24, 40, 16, 31],
       [44,  3, 45, 19,  1,  2, 42,  6],
       [35,  0, 44,  7, 19, 16, 25, 28],
       [30, 33, 19, 19, 36, 46,  0,  3],
       [18,  2,  5, 28, 45, 11, 45,  3],
       [30, 29,  3, 13, 14, 40, 43, 17]])

In [14]:
ranarr.reshape(6, -1)

array([[23, 20, 34, 39, 24, 40, 16, 31],
       [44,  3, 45, 19,  1,  2, 42,  6],
       [35,  0, 44,  7, 19, 16, 25, 28],
       [30, 33, 19, 19, 36, 46,  0,  3],
       [18,  2,  5, 28, 45, 11, 45,  3],
       [30, 29,  3, 13, 14, 40, 43, 17]])

### Create an array named "mat" .

In [15]:
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Using the array above, write a code that reproduces the desired output shown below.

In [16]:
mat[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

### Get the 1st column (index number 0) of the array above.

In [17]:
mat[0:4, 0]

array([ 1,  5,  9, 13])

### Get the values in 2nd row (index number 1) for every 2 step.

In [18]:
mat[1, [0, 2]]

array([5, 7])

### Assign 77 to every cell in 3rd column.

In [19]:
mat[0:4, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

### (a) Take 2nd row (index number 1) and 1st column (index number 0) , (b) 4th row (index number 3) and 3rd column (index number 2) .

In [20]:
mat[[1, 3],[0, 2]]

array([ 5, 77])

### Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [21]:
mat[1::2 , ::2]

array([[ 5, 77],
       [13, 77]])

### Get the sum of values smaller than 10 and values bigger than 12 in "mat".

In [22]:
mat[mat < 10]

array([1, 2, 4, 5, 6, 8, 9])

In [23]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [24]:
x = mat[mat < 10]
y = mat[mat > 12]
np.add(x, y)

array([78, 79, 81, 18, 20, 85, 25])

### Get the standard deviation (std) of the result above.

In [25]:
result = np.array([78, 79, 81, 18, 20, 85, 25])
result.std()

29.700546274093877

### Get the sum of the 2nd column in the original "mat".

In [26]:
mat = np.arange(1, 17).reshape(4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [27]:
second_column = mat[0: , 1]
second_column.sum()

32

### Get the median, mean and std of 3rd column in "mat".

In [28]:
third_column = mat[:, 2:3]
third_column

array([[ 3],
       [ 7],
       [11],
       [15]])

In [29]:
mat[2, :]

array([ 9, 10, 11, 12])

In [30]:
print(np.median([ 3,  7, 11, 15]))
print(np.median([ 9, 10, 11, 12]))

9.0
10.5


In [31]:
print(np.mean([ 3,  7, 11, 15]))
print(np.mean([ 9, 10, 11, 12]))

9.0
10.5


In [32]:
print(np.std([ 3,  7, 11, 15]))
print(np.std([ 9, 10, 11, 12]))

4.47213595499958
1.118033988749895


In [33]:
import pandas as pd

In [35]:

df = pd.read_csv("Salaries.csv")
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [36]:
df.sample()

Id EmployeeName              JobTitle   BasePay  OvertimePay  \
21751  21752    NANCY HUI  SENIOR ACCOUNT CLERK  57630.56          0.0   

       OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
21751     624.0       NaN  58254.56          58254.56  2011    NaN   

              Agency  Status  
21751  San Francisco     NaN

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [38]:
df.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

### How many different year values are there?

In [39]:
df.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [40]:
df.Year.unique()

array([2011, 2012, 2013, 2014])

### Print out max and avg values in the column of "Totalpay".

In [41]:
df.TotalPay.max()

567595.43

In [42]:
df.TotalPay.mean()

74768.321971703

### How many records in the TotalPay column are there bigger than avg TotalPay?

In [43]:
df[df.TotalPay.mean() < df.TotalPay]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

### How much does ALBERT PARDINI make money (including benefits)?

In [44]:
df.iloc[[2], 8]

2    335279.91
Name: TotalPayBenefits, dtype: float64

### Who is the lowest paid person?

In [49]:
df[df["TotalPay"].min() == df["TotalPay"]][["EmployeeName"]]

EmployeeName
148653    Joe Lopez

### What are the unique Jobs in dataset?

In [50]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

### List the top 3 least common Jobs in the dataset.

In [51]:
df["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

### How many people earned more than avg in 2012?

In [52]:
len(df[(df.TotalPayBenefits.mean() < df.TotalPayBenefits) & (df.Year == 2012)])

20366

### How many people have a title of Manager in their jobs?

In [53]:
df["JobTitle"].apply(lambda x : "manager" in x.lower()).sum()

4110

### Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe.

In [54]:
sal_new = df.iloc[:, [0, 1, 2, 7, 8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

### Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df.

In [55]:
sal_new = df.loc[: ,["EmployeeName" ,"JobTitle", "TotalPay", "TotalPayBenefits"]]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

### Print out the names of the employees who earn more than min but less than avg.

In [56]:
a = sal_new.TotalPayBenefits.min()
a

-618.13

In [57]:
b = sal_new.TotalPayBenefits.mean()
b

93692.55481056834

In [58]:
sal_new[(sal_new.TotalPayBenefits < b) & (sal_new.TotalPayBenefits > a)][["EmployeeName", "TotalPayBenefits"]]

EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]